---
title: Instalación de Raspbian usando la Raspberry Pi
hero_image: images / banner.png
description: Instalación de Raspbian usando la Raspberry Pi
version: 4
listed: true
copyedit: false
last_tested: "2020-03-10"
steps:
  - 
    title: Introducción
