---
title: تثبيت Raspbian باستخدام Raspberry Pi
hero_image: images/banner.png
description: تثبيت راسبيان باستخدام راسبري باي
version: 4
listed: true
copyedit: false
last_tested: "2020-03-10"
steps:
  - 
    title: المقدمة
